# create and appl the new environment with
#
# ```
# conda env create -f environment.yml
# conda activate dlhproj
# ```
#
# then, manually install 2 packages with pip:
#
# ```
# pip install biosppy~=2.1.2 tensorflow-addons
# ```
name: dlhproj

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy~=1.26.4
  - pandas~=2.2.1
  - scipy~=1.12.0
  # - biosppy~=2.1.2
  - mne~=1.6.1
  - keras < 2.16
  - tensorflow~=2.15
  # - tensorflow-addons
  - scikit-learn~=1.4.1.post1
  - python-dateutil~=2.8.2
