# create and appl the new environment with
#
# ```
# conda env create -f environment.yml
# conda activate dlhproj
# ```
#
# then, manually install 2 packages with pip:
#
# ```
# pip install biosppy~=2.1.2 tensorflow-addons
# ```
name: dlhproj

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy~=1.26.4
  - pandas~=2.2.1
  - scipy~=1.12.0

  - mne~=1.6.1
  - keras < 2.16
  - tensorflow~=2.15
  - scikit-learn~=1.4.1.post1
  - python-dateutil~=2.8.2
  #####
  # these two packages are not installable with conda. see above for
  # how to install and apply the conda-powered environment, and then
  # install them with pip
  #####
  #
  # - tensorflow-addons
  # - biosppy~=2.1.2

dev-dependencies:
  - pyright
  - pylint
