# create and appl the new environment with
#
# ```
# conda env create -f environment.yml
# conda activate dlhproj

name: dlhproj

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy~=1.26.4
  - pandas~=2.2.1
  - scipy~=1.12.0

  - mne~=1.6.1
  - keras < 2.16
  - tensorflow~=2.15.1
  - scikit-learn~=1.4.1.post1
  - python-dateutil~=2.8.2
  - pyright
  - pylint
  # these two packages are not installable with conda, so install with pip
  - pip
  - pip:
    - tensorflow-addons
    - biosppy~=2.1.2
  